### ISSUE TITLE
Push View 

### ISSUE THREAD

**Issue by dromerobarria** [kukushi/SideMenu#3] opened 2018-03-26 18:41 UTC
Hi, really nice side menu.

I have a problem when I push to a view controller ,I can acces a view through the side menu or with a push , but when i call the side menu from a push view  with the "sm_sideMenuController" it wont work , only when i call the view  from the side menu i cant keet calling the side menu.

Thanks

**Comment by kukushi** [comment] 2018-03-27 03:40
Sorry, I don’t quite understand how you are using it.
It will be helpful if you can explain it with code.

**Comment by kukushi** [comment] 2018-03-30 05:20
@dromerobarria Hello?

**Comment by kukushi** [comment] 2018-03-31 12:04
OK, it seems that I had figured out where the issue is.

The `sideMenuController` will return `nil` if you call it inside the `viewDidLoad()`  in the pushed view controller. The cause is the `navigationController` is returning `nil` in the `viewDidLoad` because the view controller is not yet inserted into the navigation controller. Therefore, `sideMenuController` will return `nil`, too.

**Comment by dromerobarria** [comment] 2018-03-31 16:13
Sorry for the late answer and thanks for the responses.

My main problem is in the flow of the app , I have a first view and a second view,  I call the second view with a navigationController from the first view (with a show and the second view has navigation), and in both view Im must be able to call the SideMenu, but for reason it wont work in the second view and when i call the method of the SideMenu the app stuck. 

I must said that in the sideMenu Im able to call both views and when I do it from the SideMenu it show the menu and no problem only happend if i do a show to the secondView and the call the SideMenu. 

I solved it calling the secondview always with the method of the SideMenu and without using present or show.

**Comment by kukushi** [comment] 2018-03-31 16:38
@dromerobarria 
Oh. I also found that there was an issue may freeze the app when getting the `sideMenuController` which was resolved in the new version (0.4.0).
Give it a try.

**Closed** 2018-04-02 17:36 UTC
