### ISSUE TITLE
2 Side menus in different pages

### ISSUE THREAD

**Issue by Haidarooz** [kukushi/SideMenu#28] opened 2018-12-19 22:20 UTC
Hello kukushi, thank you for the great work,

Is it possible to have a second side menu in another page? my app has one side menu in the main page and it opens from the left.. I want to add another side menu in the next page but it should slide from the right.. and have different content.

Possible?

Thank you

**Comment by kukushi** [comment] 2018-12-20 03:35
Duplicate of #19.

**Closed** 2018-12-20 03:37 UTC
